# Generated by Django 4.2.30 on 2026-09-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('fav_code', models.CharField(db_column='FAV_CODE', max_length=20, primary_key=True, serialize=False, verbose_name='즐겨찾기 코드')),
            ],
            options={
                'verbose_name': '즐겨찾기',
                'verbose_name_plural': '즐겨찾기 목록',
                'db_table': 'FAVORITE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('itinerary_code', models.CharField(db_column='ITINERARY_CODE', max_length=20, primary_key=True, serialize=False, verbose_name='일정 코드')),
                ('itinerary_title', models.CharField(blank=True, db_column='ITINERARY_TITLE', max_length=255, null=True, verbose_name='일정 제목')),
                ('itinerary_date', models.DateField(db_column='ITINERARY_DATE', verbose_name='일정 일자')),
                ('companion', models.CharField(blank=True, db_column='COMPANION', max_length=20, null=True, verbose_name='동행')),
                ('pet_accompanied', models.BooleanField(db_column='PET_ACCOMPANIED', verbose_name='반려동물 동반 여부')),
                ('memo', models.CharField(blank=True, db_column='MEMO', max_length=255, null=True, verbose_name='메모')),
            ],
            options={
                'verbose_name': '여행 일정',
                'verbose_name_plural': '여행 일정 목록',
                'db_table': 'ITINERARY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_code', models.CharField(db_column='REGION_CODE', max_length=20, primary_key=True, serialize=False, verbose_name='지역 코드')),
                ('region_name', models.CharField(db_column='REGION_NAME', max_length=255, verbose_name='지역명')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역 목록',
                'db_table': 'REGION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_code', models.CharField(db_column='REVIEW_CODE', max_length=20, primary_key=True, serialize=False, verbose_name='후기 코드')),
                ('rating', models.IntegerField(db_column='RATING', verbose_name='평점')),
                ('create_date', models.DateTimeField(db_column='CREATE_DATE', verbose_name='작성 일시')),
                ('content', models.CharField(blank=True, db_column='CONTENT', max_length=255, null=True, verbose_name='후기 내용')),
            ],
            options={
                'verbose_name': '후기',
                'verbose_name_plural': '후기 목록',
                'db_table': 'REVIEW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('spot_code', models.CharField(db_column='SPOT_CODE', max_length=20, primary_key=True, serialize=False, verbose_name='관광지 코드')),
                ('t_name', models.CharField(db_column='T_NAME', max_length=255, verbose_name='관광지명')),
                ('address', models.CharField(db_column='ADDRESS', max_length=255, verbose_name='주소')),
                ('entry_fee', models.IntegerField(db_column='ENTRY_FEE', verbose_name='입장료')),
                ('parking_info', models.CharField(blank=True, db_column='PARKING_INFO', max_length=20, null=True, verbose_name='주차 정보')),
                ('operating_hours', models.CharField(db_column='OPERATING_HOURS', max_length=255, verbose_name='운영 시간')),
                ('phone', models.CharField(db_column='PHONE', max_length=20, verbose_name='문의 전화번호')),
                ('pet_allowed', models.IntegerField(db_column='PET_ALLOWED', verbose_name='반려동물 동반 가능 여부')),
                ('image', models.ImageField(blank=True, db_column='IMAGE', null=True, upload_to='tourist_spots/', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '관광지',
                'verbose_name_plural': '관광지 목록',
                'db_table': 'TOURISTSPOT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(db_column='USER_ID', max_length=20, primary_key=True, serialize=False, verbose_name='회원 ID')),
                ('nickname', models.CharField(db_column='NICKNAME', max_length=20, verbose_name='닉네임')),
                ('email', models.CharField(db_column='EMAIL', max_length=255, verbose_name='이메일')),
                ('pw', models.CharField(db_column='PW', max_length=20, verbose_name='비밀번호')),
                ('join_date', models.DateField(blank=True, db_column='JOIN_DATE', null=True, verbose_name='가입일자')),
                ('status', models.CharField(db_column='STATUS', default='정상', max_length=20, verbose_name='회원 상태')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원 목록',
                'db_table': 'USERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_condition', models.CharField(db_column='WEATHER_CONDITION', max_length=20, verbose_name='기상 상태')),
                ('forecast_date', models.DateField(db_column='FORECAST_DATE', verbose_name='예보 날짜')),
                ('temp_high', models.IntegerField(blank=True, db_column='TEMP_HIGH', null=True, verbose_name='최고 기온')),
                ('precip_pct', models.IntegerField(blank=True, db_column='PRECIP_PCT', null=True, verbose_name='강수 확률(%)')),
            ],
            options={
                'verbose_name': '날씨 캐시',
                'verbose_name_plural': '날씨 캐시 목록',
                'db_table': 'WEATHERCACHE',
                'managed': False,
            },
        ),
    ]
